DROP TABLE centralized_throughput_stat;
CREATE TABLE `centralized_throughput_stat` (
  `ID` BIGINT(50) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `UNIT_ID` BIGINT(50) NOT NULL COMMENT '',
  `START_TIME` DATETIME NOT NULL COMMENT '',
  `END_TIME` DATETIME NOT NULL COMMENT '',
  `TYPE` VARCHAR(10) NOT NULL COMMENT 'type',
  `NUMBER` BIGINT(50) NOT NULL COMMENT '',
  `SIZE` BIGINT(50) NOT NULL COMMENT '',
  `CREATED` DATETIME NOT NULL COMMENT '创建时间',
  `MODIFIED` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  KEY (`END_TIME`)
) ENGINE=INNODB AUTO_INCREMENT=27812 DEFAULT CHARSET=utf8 COMMENT=''